New Spezi Standard Implementation
StanfordSpezi/SpeziQuestionnaire pull request #7
Opened 2023-07-22 00:26 UTC by niallkehoe

# *New Spezi Standard Implementation*

## :recycle: Current situation & Problem
*Currently, the SpeziQuestionnaire module lacks support for the new Spezi Standard released in Spezi 0.7.0*
*This PR implements the improvements mentioned in [https://github.com/StanfordSpezi/Spezi/pull/73](Pull 73) *

## :bulb: Proposed solution
*Update the codebase to the newest Spezi 0.7.0*

## :gear: Release Notes 
This feature will allow for greater flexibility when using Spezi Questionnaire.

```
/// A Standard which all Spezi Questionnaires must follow
public protocol QuestionnaireConstraint: Standard {
    
    /// Adds a new `QuestionnaireResponse` to the ``QuestionnaireDataSource``
    /// - Parameter response: The `QuestionnaireResponse` that should be added.
    func add(_ response: QuestionnaireResponse) async
}
```

### Related PRs
*See [https://github.com/StanfordSpezi/Spezi/pull/73](Pull 73) in Spezi for details*

### Testing
*Passes all tests*

### Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [ ✅ ] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

2023-07-25 19:47 UTC, PSchmiedmayer commented
@PSchmiedmayer Take a look at the test coverage

2023-07-28 06:20 UTC, PSchmiedmayer requested changes
@niallkehoe Thank you for improving Spezi and bringing Spezi Questionnaire up to Spezi 0.7.0! Thank you for removing the constraint and simplifying the questionnaire module!

I have taken a look at the failing UI tests and it seems like the main reason was the SwiftLint task in the Xcode project that just lined all downloaded dependencies. I have added the right ignores in the SwiftLint files. I have also explicitly added the package target to the list of build steps to ensure that the code coverage is correctly reported.

I had a few comment rating from style-level comments, documentation, to the UI tests to verify the functionality. Once those comments are addressed we can merge the PR and tag a new release. Feel free to reach out if you have any questions or comments regarding the feedback, always happy to help and support!

Looking forward to your first Spezi contribution, more to come! 🚀

2023-07-28 21:36 UTC, niallkehoe commented on Sources/SpeziQuestionnaire/QuestionnaireDataSource.swift
> +/// You can use the ``QuestionnaireDataSource/init()`` initializer of you use the Questionnaire standard in your Spezi application:
Not sure what you had in mind. Would "QuestionnaireDataSource uses QuestionnaireConstraint which can be customized by conforming your standard to QuestionnaireConstraint"?

2023-07-31 18:30 UTC, niallkehoe commented on Tests/UITests/TestApp/TestAppDelegate.swift
> +}
I tried including a counter which increases on add(), however in this branch and main the template application never finishes the questionnaire. After the last question, there is a breakpoint on QuestionnaireView 78: questionnaireDataSource.add(questionnaireResponse): 
2023-07-31 11:14:57.820054-0700 TestApp[42944:2475753] SwiftUI/EnvironmentObject.swift:82: Fatal error: No ObservableObject of type QuestionnaireDataSource found. A View.environmentObject(_:) for QuestionnaireDataSource may be missing as an ancestor of this view.

2023-08-03 10:58 UTC, vishnuravi commented
Thank you @niallkehoe!

2023-08-06 19:31 UTC, PSchmiedmayer approved these changes
Thank you for all the changes and great additions @niallkehoe! I only had two very minor change requests that make the code a bit cleaner and ensure that you can reduce some of the complexity in the test views.
Once those are addressed you can resolve the conversations and merge the PR. Thank you for the contribution and taking the time to improve Spezi! 🚀

2023-08-06 19:31 UTC, PSchmiedmayer commented on Sources/SpeziQuestionnaire/QuestionnaireConstraint.swift
> +    func add(_ response: QuestionnaireResponse) async
In sync to the HealthKit PR, I would suggest that we slightly adjust the function signature here to make it easier to multiplex between the different add methods we might need to implement in a `Standard` conforming to the different constraints:
```suggestion
    func add(response: QuestionnaireResponse) async
```

2023-08-06 19:31 UTC, PSchmiedmayer commented on Tests/UITests/TestApp/ContentView.swift
> +            }
Now that you have enforced that `surveyResponseCount` can only be accessed from the `@MainActor`, Swift is actually smart enough to see that this closure will also always be executed in the main actor (enforced by SwiftUI) and you can therefore access the property without the need for an `await`:
```suggestion
        Text("No. of surveys complete: \(standard.surveyResponseCount)")
```

2023-08-06 19:31 UTC, PSchmiedmayer commented on Tests/UITests/TestApp/ContentView.swift
> +    @State var surveyResponseCount = 0
Once you made the changes to the `Text`, you can remove this property there 🚀

2023-08-07 21:52 UTC, merged